server:
    port: 8585
    contextPath: /app

liquibase:
    context: master
    change-log: classpath:/config/liquibase/liquibase.xml
    parameters: {"DBMS":"oracle","varcharType":"char","currentTimeStamp":"sysdate", "autoIncrement":"false","key":"key"}

spring:
    datasource:
        dataSourceClassName: oracle.jdbc.xa.client.OracleXADataSource
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: app_ddl
        password: app_ddl
        maximumPoolSize: 10